### ISSUE TITLE
SNAPVX didn't work.

### ISSUE THREAD

**Issue by newera912** [snap-stanford/snapvx#11]
I try to run the example code(OS: Windows 10 X64, Python2.7 X64), the SNAPVX part is not work. Error pointed out the snap graph have no attribute of solve(). Can someone provide the problem? I checked the CVXPY and SNAP woking well. But they cannot work together. I install the snapvx.py by running setup.py.

Error Message: ---------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 495, in prepare
    '**parents_main**', file, path_name, etc
  File "F:\workspace\SNAP_VX\examples\snapVX_example.py", line 23, in <module>
    gvx.Solve()
  File "C:\Python27\lib\site-packages\snapvx.py", line 110, in Solve
    self.**SolveADMM(rho, maxIters, verbose)
  File "C:\Python27\lib\site-packages\snapvx.py", line 259, in __SolveADMM
    pool = multiprocessing.Pool(num_processors)
  File "C:\Python27\lib\multiprocessing__init**.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "C:\Python27\lib\multiprocessing\pool.py", line 159, in **init**
    self._repopulate_pool()
  File "C:\Python27\lib\multiprocessing\pool.py", line 223, in _repopulate_pool
    w.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_line
    is not going to be frozen to produce a Windows executable.''')
RuntimeError: 
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

```
        This probably means that you are on Windows and you have
        forgotten to use the proper idiom in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce a Windows executable.
```

**Comment by newera912** [comment]
The example code:

from snapvx import *

#Create new graph
gvx = TGraphVX()

#Use CVXPY syntax to define a problem
x1 = Variable(1, name='x1')
obj = square(x1)
#Add Node 1 with the given objective, with the constraint that x1 <= 10
gvx.AddNode(1, Objective=obj, Constraints=[x1 <= 10])

#Similarly, add Node 2 with objective |x2 + 3|
x2 = Variable(1, name='x2')
obj2 = abs(x2 + 3)
gvx.AddNode(2, obj2, [])

#Add an edge between the two nodes, 
#Define an objective, constraints using CVXPY syntax
gvx.AddEdge(1, 2, Objective=square(norm(x1 - x2)), Constraints=[])

#Solve the problem, and print the solution
gvx.Solve()
print gvx.PrintSolution()

**Comment by newera912** [comment]
If changed the code , be func(). then code can't recognized the .Solve() function.

Code:+++++++++++++++++++++++++++++++++++++++++++++++++++

from snapvx import *

def snapcvx():
    #Create new graph
    gvx = TGraphVX()  
    #Use CVXPY syntax to define a problem
    x1 = Variable(1, name='x1')
    obj = square(x1)
    #Add Node 1 with the given objective, with the constraint that x1 <= 10
    gvx.AddNode(1, Objective=obj, Constraints=[x1 <= 10])  
    #Similarly, add Node 2 with objective |x2 + 3|
    x2 = Variable(1, name='x2')
    obj2 = abs(x2 + 3)
    gvx.AddNode(2, obj2, [])  
    #Add an edge between the two nodes, 
    #Define an objective, constraints using CVXPY syntax
    gvx.AddEdge(1, 2, Objective=square(norm(x1 - x2)), Constraints=[])  
    gvx.Solve() #Solve the problem
    gvx.PrintSolution() #Print entire solution on a node-by-node basis
    print "x1 = ", x1.value, "; x2 = ", x2.value #Print the solutions of individual variables

def main():
    snapcvx()  
if **name** == '**main**':
    main()

Error Messages:-------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "F:/workspace/SNAP_VX/examples/snapVX_example.py", line 30, in <module>
    main()
  File "F:/workspace/SNAP_VX/examples/snapVX_example.py", line 27, in main
    snapcvx()
  File "F:/workspace/SNAP_VX/examples/snapVX_example.py", line 22, in snapcvx
    gvx.Solve() #Solve the problem
  File "C:\Python27\lib\site-packages\snapvx.py", line 139, in Solve
    Verbose)
  File "C:\Python27\lib\site-packages\snapvx.py", line 326, in __SolveADMM
    pool.map(ADMM_x, node_list)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value

**Comment by davidhallac** [comment]
Hmmm. Did you get any warnings when you ran setup.py to install snapvx? If so, can you include any messages the system printed out?

**Comment by newera912** [comment]
Hi, davidhallac
I tried both version, SNAPVX 1.0 and 2.0. When install snapvx no warnings.

Below is cmd line snap shot:

PS F:\workspace\SNAP_VX\install\snapvx-0.2> python setup.py install
running install
running build
running build_py
creating build
creating build\lib
copying snapvx.py -> build\lib
running install_lib
running install_egg_info
Removing C:\Python27\Lib\site-packages\snapvx-0.2-py2.7.egg-info
Writing C:\Python27\Lib\site-packages\snapvx-0.2-py2.7.egg-info

**Comment by davidhallac** [comment]
Okay, weird. It seems like it might be an issue with multiprocessing on windows acting differently than on linux/mac. It's most likely some small setting that needs to be changed or something...

I will leave this issue "open" and look into it, but in the meantime do you have a mac/linux machine that you can run SnapVX on?

**Comment by newera912** [comment]
Can you make SnapVX support Windows? I tried on ubuntu it works now. 
If Snapvx support windows will be great.

**Comment by newera912** [comment]
It seems like in Windows threads create or construct under this clause: 
"if **name** == '**main**':"
             .....

*********_example code:**_*****************
from multiprocessing import Process
import os

def info(title):
    print title
    print 'module name:', **name**
    if hasattr(os, 'getppid'):  # only available on Unix
        print 'parent process:', os.getppid()
    print 'process id:', os.getpid()

def f(name):
    info('function f')
    print 'hello', name

if **name** == '**main**':
    info('main line')
    p = Process(target=f, args=('bob',))
    p.start()
    p.join()

**Comment by abhisg** [comment]
@newera912 could you try running the setup after extracting files from here https://github.com/abhisg/snapvx/archive/master.zip and check if your code works ?

**Comment by newera912** [comment]
@abhisg  Thank you for your update. I uninstalled the old one ,and installed the new version.
Yes the multi process error gone, but the new error coming up:
I want to comment that line and run, but the file snapvx.py can't be change.
Error Message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "F:/workspace/SNAP_VX/examples/snapVX_example.py", line 22, in <module>
    gvx.Solve() #Solve the problem
  File "C:\Python27\lib\site-packages\snapvx.py", line 147, in Solve
    Verbose)
  File "C:\Python27\lib\site-packages\snapvx.py", line 450, in __SolveADMM
    if num_iterations <= maxIters:
UnboundLocalError: local variable 'num_iterations' referenced before assignment

**Comment by abhisg** [comment]
@newera912 please try again from the same zip file

**Comment by newera912** [comment]
@abhisg  Yes it success. no errors. But the result is different than linux machine I don't why.Run the same sample code I mentioned above

Linux:
Status: Optimal
Total Objective: 2.500335
Node 1:
  x1 [-0.51704776]
Node 2:
  x2 [-1.0237034]
x1 =  -0.517047763842 ; x2 =  -1.02370340103

Windows:
Status: None
Total Objective: 3.000000
Node 1:
  x1 [ 0.]
Node 2:
  x2 [ 0.]
x1 =  0.0 ; x2 =  0.0

**Comment by abhisg** [comment]
Hmm it seems like the execution is incorrect. Please use the linux version for now. We will try and fix the issue on windows as quickly as possible

**Comment by abhisg** [comment]
@newera912 the problem seems to arise because windows does not support forking due to which multiprocessing Pool is called over and over again till all your physical memory is exhausted. I am listing a possible fix below which you have probably tried before. If this does not work could you paste a traceback of the error you get ?

``` python
import multiprocessing
from snapvx import *

#Create new graph
gvx = TGraphVX()

#Use CVXPY syntax to define a problem
x1 = Variable(1, name='x1')
obj = square(x1)
#Add Node 1 with the given objective, with the constraint that x1 <= 10
gvx.AddNode(1, Objective=obj, Constraints=[x1 <= 10])

#Similarly, add Node 2 with objective |x2 + 3|
x2 = Variable(1, name='x2')
obj2 = abs(x2 + 3)
gvx.AddNode(2, obj2, [])

#Add an edge between the two nodes, 
#Define an objective, constraints using CVXPY syntax
gvx.AddEdge(1, 2, Objective=square(norm(x1 - x2)), Constraints=[])

#Solve the problem, and print the solution
if __name__ == '__main__':
         multiprocessing.freeze_support()
         gvx.Solve()
         print gvx.PrintSolution()
```

**Comment by newera912** [comment]
Run the new example code ,No error occurs, but result is not right,
Status: None
Total Objective: 3.000000
Node 1:
  x1 [ 0.]
Node 2:
  x2 [ 0.]
None

**Comment by abhisg** [comment]
Did you run with the older version ? (The one which was giving errors earlier)

**Comment by newera912** [comment]
Yes, I used the old version of snapvx, try the both version. same. No errors but the result is not correct.

**Comment by abhisg** [comment]
@newera912 please download the zip file from https://github.com/abhisg/snapvx . The code should now run without any issues.

**Comment by newera912** [comment]
Thank you, it is working right now.Result is right
Out put:
Status: Optimal
Total Objective: 2.500335
Node 1:
  x1 [-0.51704776]
Node 2:
  x2 [-1.0237034]
None
