### ISSUE TITLE
Two unconnected nodes sharing a variable

### ISSUE THREAD

**Issue by tridao** [snap-stanford/snapvx#2]
Hi, 

Can two nodes share a variable if they have no edge between them? I seem to get strange results in such cases. For example, this snippet:

```
from snapvx import *

gvx = TGraphVX()
x = Variable(name='x')
gvx.AddNode(1, square(x))
gvx.AddNode(2, square(x - 1))
gvx.Solve(useADMM=True)
gvx.PrintSolution()
```

```
Total Objective: 1.000000
Node 1:
  x [ 0.]
Node 2:
   x [ 1.]
```

**Comment by davidhallac** [comment]
Hi Tri,

We currently do not support two nodes sharing a variable without an edge between them. Adding an edge between the two nodes would get your problem to converge (to within the stopping criteria), as follows:

``` python
from snapvx import *

gvx = TGraphVX()
x = Variable(name='x')
gvx.AddNode(1, square(x))
gvx.AddNode(2, square(x - 1))
gvx.AddEdge(1,2)
gvx.Solve(useADMM=True)
gvx.PrintSolution()
```

In general, though, SnapVX works better when each node has separate variables. So, for your example above, you could replicate the variable x (calling the copy, say, x2) and impose a consensus constraint in the edge between them. You could write it like this:

``` python
gvx = TGraphVX()
x = Variable(name='x')
x2 = Variable(name='x')
gvx.AddNode(1, square(x))
gvx.AddNode(2, square(x2 - 1))
gvx.AddEdge(1,2, Constraints=[x == x2])
gvx.Solve(useADMM=True)
gvx.PrintSolution()
```

It's a bit clunky for now, so if a lot of people use consensus constraints like this, we can come up with a "fast" way to impose this condition.

David
