### ISSUE TITLE
http://snap.stanford.edu/snapvx/:  example 2

### ISSUE THREAD

**Issue by keithbriggs** [snap-stanford/snapvx#26]
Running example 2 gives:

Traceback (most recent call last):
  File "try_snapvx_01.py", line 27, in <module>
    gvx.Solve(verbose=True)
TypeError: Solve() got an unexpected keyword argument 'verbose'

Deleting this argument gives:

Status: Optimal
Total Objective: 57.155315
Node 0:
  x [ 0.29378266 -0.26524219 -0.25250324 -0.23300168  0.41298769 -0.86914119  0.40773391  0.08331969  0.37224637  0.30800445]
Node 1:
  x [ 0.28712282 -0.61276469 -0.22615739 -0.08915738  0.46016299 -0.65311469 -0.02752935  0.08996956  0.30531097  0.49308243]
Node 2:
  x [-0.16487666  0.04105045 -0.01458014  0.04529752  0.42459157 -0.60412203  0.13055647  0.13764805  0.29633032  0.39071433]
Node 3:
  x [-0.03418349 -0.27205432 -0.26004528 -0.14080719  0.21878818 -0.51484094 -0.02752153  0.30287523  0.54348138  0.44594498]
Node 4:
  x [-0.0570535  -0.29944952 -0.27701554  0.28553805  0.2666139  -0.53738026  0.11731259  0.68169612  0.35534438  0.44016973]
Node 5:
  x [ 0.01863543 -0.20670528 -0.28652516 -0.03612443  0.26639766 -0.45263951  0.19732264  0.41410293  0.38650289  0.45014487]
Node 6:
  x [-0.18936785  0.04308614 -0.07898234 -0.00796519  0.32889441 -0.47519744  0.26286999  0.57228709  0.68563219  0.12939756]
Node 7:
  x [-0.15645225 -0.25574082 -0.15371909  0.10040179  0.32351306 -0.69226112  0.04055426  0.40433945  0.3745141   0.45589338]
Node 8:
  x [ 0.03211502 -0.28758238 -0.1845991   0.0305872   0.30857288 -0.50723567  0.00627196  0.33058891  0.33684959  0.52280612]
Node 9:
  x [ 0.13993065 -0.21152357 -0.22114066 -0.05560236  0.3347094  -0.4827472   0.01202981  0.29923677  0.24623348  0.4842382 ]
Traceback (most recent call last):
  File "try_snapvx_01.py", line 30, in <module>
    gvx.Solve(useADMM=False) # Solve serially (no ADMM)
TypeError: Solve() got an unexpected keyword argument 'useADMM'

Also, a space (required for readability) is missing after every "#" comment symbol.

**Comment by davidhallac** [comment]
Just to clarify, you're talking about Example 2 on the SnapVX website (http://snap.stanford.edu/snapvx/), right?

Yes, you are 100% correct here. The parameters in that example were accidentally "verbose" and "useADMM", rather than "Verbose" and "UseADMM". Thanks for pointing it out!

We have updated the website to fix this error, and have also added the space after every "#" comment symbol for readability. Everything should be working now. Please let us know if you find anything else that looks wrong.

Thanks!

**Comment by keithbriggs** [comment]
Thanks - yes, that's the example, as the subject line says.
Keith

**Comment by davidhallac** [comment]
Perfect, thanks again for letting us know!
