### ISSUE TITLE
Test running so slow

### ISSUE THREAD

**Issue by jingmiao93** [snap-stanford/snapvx#27]
When I follow the guidelines to run Tests "./test_basic.sh, it has been running hours and still running. Is it supposed to be this slow? Is there any way that I can speed up?

**Comment by davidhallac** [comment]
No, that should not be happening. Do you know what test you are getting stuck on? What does the terminal output look like?

**Comment by jingmiao93** [comment]
<img width="767" alt="screen shot 2016-11-19 at 4 58 55 am" src="https://cloud.githubusercontent.com/assets/23463818/20455633/2e93b726-ae15-11e6-888d-53caadd5a7cb.png">
<img width="769" alt="screen shot 2016-11-19 at 4 58 33 am" src="https://cloud.githubusercontent.com/assets/23463818/20455634/2e951512-ae15-11e6-8e47-351cb637bd9b.png">

These are the kind of output I get by running the Test. It takes more than an hour to do a single test.

**Comment by jingmiao93** [comment]
And the tests I am stuck on are those with "ok"s with space.

**Comment by davidhallac** [comment]
Hmm, that might be a threadlocking issue... Can you let us know what system you're running SnapVX on?

For now, if the tests are coming back OK, feel free to start using the software since it seems to have installed properly, but we will look into this and see if we can figure out why the units are so slow.

**Comment by jingmiao93** [comment]
I am using Mac OS X El Capitian (10.11.4). But I found that my CPU memory (8GB) is probably full.... Here is a screenshot. Is it because the network runs super slow on swap?
<img width="801" alt="screen shot 2016-11-19 at 4 26 39 pm" src="https://cloud.githubusercontent.com/assets/23463818/20459434/bfa1c32e-ae75-11e6-90d6-e7167690673e.png">

**Comment by abhisg** [comment]
Could you pull the latest patch and confirm that the tests are running seamlessly now ?

**Comment by jingmiao93** [comment]
I just try to "import snapvx" in my Python 2.7, but it produces "Fatal Python error: PyThreadState_Get: no current thread". I can run the test cases in Tests (though slow) successfully. Is there a problem with my installation?

**Comment by davidhallac** [comment]
I think that error comes from Snap.py. See here for a troubleshooting guide for how to fix it: https://github.com/snap-stanford/snap/issues/88

Let us know if that fixes things. The SnapVX tests should run quickly if you pull the newest version on the github.
