### ISSUE TITLE
installing snapvx (and snap) on server

### ISSUE THREAD

**Issue by jingmiao93** [snap-stanford/snapvx#29]
Hi, I was trying to install snapvx(snap) on Stanford Corn using "pip install --user setup.py", but it gave the following error: 
Collecting setup.py
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command."

I tried to move all the dependencies of snap(snapvx) (e.g. cvxpy) packages under the same folder, but it still gives the same output. Am I using the wrong install method?

Thank you so much!

**Comment by davidhallac** [comment]
SnapVX does not currently support pip download. The easiest way to install SnapVX on a server like that is that is to clone the github repo directly ("git clone git@github.com:snap-stanford/snapvx.git"). Another option is to download the package locally on your machine (from here: http://snap.stanford.edu/snapvx/release/), then to scp the SnapVX folder over to the server.
